### ISSUE TITLE
Remove compensation display for guests

### ISSUE THREAD

**Issue by scito** [lobbywatch/website#20]
Do not show compensations for guests, only for parliamentarians

![image](https://user-images.githubusercontent.com/876593/70124299-c5df8900-1674-11ea-99b4-1baf645ea8dd.png)

**Comment by tpreusse** [comment]
Happened because the API returned `verguetungen_jahr` / `verguetungen_pro_jahr` objects for guests: https://cms.lobbywatch.ch/data.php?q=de%2Fdata%2Finterface%2Fv1%2Fjson%2Ftable%2Fzutrittsberechtigung%2Faggregated%2Fid%2F567&includeMetaData=1&limit=none&lang=de

Added frontend logic to only display it for type `Parliamentarian`.
